"""Domain entities and business rules (zero external dependencies)."""

from runner.domain.config import (
    DiscordConfig,
    GitConfig,
    LifecycleConfig,
    ModelConfig,
    ModelEntry,
    PresenceConfig,
    ProjectConfig,
    RunnerConfig,
    TokenBudgetConfig,
    UIConfig,
    VerificationConfig,
    WorkerConfig,
)
from runner.domain.exceptions import (
    CleanSlateError,
    CommandNotFoundError,
    ConfigError,
    DoctorError,
    GitError,
    NonInteractiveError,
    QueueLockError,
    SignalFormatError,
    SpecFormatError,
    StateFormatError,
    TicketFormatError,
    TicketRunnerError,
    UserAbortError,
    DiscordGatewayError,
)
from runner.domain.failure_analyser import (
    FAILURE_LABELS,
    LABEL_CASCADE,
    LABEL_ENV,
    LABEL_FLAKY,
    LABEL_HANG,
    FailureDiagnostic,
    analyse,
    build_isolation_command,
    extract_error_fingerprints,
    extract_test_identifiers,
    interpolate_isolation_command,
    render_diagnostic_report,
)
from runner.domain.ring_buffer import (
    MAX_RING_BUFFER_ENTRIES,
    RingBuffer,
    VALID_RING_BUFFER_SOURCES,
)
from runner.domain.runtime_paths import DEFAULT_AGENT_DIR, RuntimePaths
from runner.domain.signal import (
    QuestionSignal,
    QuestionType,
    ReadySignal,
    SignalStatus,
)
from runner.domain.state import (
    RunnerState,
    StateStatus,
    TokenState,
)
from runner.domain.telemetry import (
    BudgetAction,
    BudgetMonitor,
    TokenUsage,
    WorkerEvent,
    effective_ceiling,
)
from runner.domain.ticket import Ticket, TicketStatus, parse_ticket_status

__all__ = [
    "DEFAULT_AGENT_DIR",
    "BudgetAction",
    "BudgetMonitor",
    "CleanSlateError",
    "CommandNotFoundError",
    "ConfigError",
    "DiscordConfig",
    "DiscordGatewayError",
    "DoctorError",
    "FAILURE_LABELS",
    "FailureDiagnostic",
    "GitConfig",
    "GitError",
    "LABEL_CASCADE",
    "LABEL_ENV",
    "LABEL_FLAKY",
    "LABEL_HANG",
    "LifecycleConfig",
    "MAX_RING_BUFFER_ENTRIES",
    "ModelConfig",
    "ModelEntry",
    "NonInteractiveError",
    "PresenceConfig",
    "ProjectConfig",
    "QueueLockError",
    "QuestionSignal",
    "QuestionType",
    "ReadySignal",
    "RingBuffer",
    "RunnerConfig",
    "RunnerState",
    "RuntimePaths",
    "SignalFormatError",
    "SignalStatus",
    "SpecFormatError",
    "StateFormatError",
    "StateStatus",
    "Ticket",
    "TicketFormatError",
    "TicketStatus",
    "TokenBudgetConfig",
    "TokenState",
    "TokenUsage",
    "UIConfig",
    "UserAbortError",
    "VALID_RING_BUFFER_SOURCES",
    "VerificationConfig",
    "WorkerConfig",
    "WorkerEvent",
    "analyse",
    "build_isolation_command",
    "effective_ceiling",
    "extract_error_fingerprints",
    "extract_test_identifiers",
    "interpolate_isolation_command",
    "parse_ticket_status",
    "render_diagnostic_report",
]
